import { describe, expect, it, vi } from "vitest"
import { VoiceSaveQueue, VoiceFinalOrder, reduceVoiceCaption } from "@/lib/research-browser-voice-client"

describe("browser voice evidence queue", () => {
  it("caps cumulative partial captions before retaining oversized provider data", () => {
    expect(() => reduceVoiceCaption([], { type: "response.output_audio_transcript.delta", item_id: "large", delta: "x".repeat(80_001) })).toThrow("caption limit")
  })
  it("releases an empty final without inventing transcript evidence", async () => {
    const persist = vi.fn().mockResolvedValue(undefined)
    const order = new VoiceFinalOrder(persist)
    order.observe({ type: "response.output_item.added", item: { id: "cancelled", role: "assistant", content: [] } })
    expect(order.unresolved).toBe(true)
    await order.finalize({ providerEventId: "output:cancelled", role: "INTERVIEWER", content: "" })
    expect(order.unresolved).toBe(false)
    expect(persist).not.toHaveBeenCalled()
  })
  it("bounds unresolved item buffering and ignores text-only pacing items", () => {
    const order = new VoiceFinalOrder(vi.fn())
    order.observe({ type: "conversation.item.added", item: { id: "pacing", role: "user", content: [{ type: "input_text" }] } })
    expect(order.unresolved).toBe(false)
    for (let index = 0; index < 200; index += 1) order.observe({ type: "response.output_item.added", item: { id: String(index), role: "assistant" } })
    expect(() => order.observe({ type: "response.output_item.added", item: { id: "overflow", role: "assistant" } })).toThrow("buffer limit")
  })
  it("holds a later interviewer and attachment until the earlier participant final arrives", async () => {
    const persist = vi.fn().mockResolvedValue(undefined)
    const order = new VoiceFinalOrder(persist)
    order.observe({ type: "conversation.item.added", item: { id: "user", role: "user", content: [{ type: "input_audio" }] } })
    order.observe({ type: "response.output_item.added", item: { id: "assistant", role: "assistant", content: [] } })
    const assistant = order.finalize({ providerEventId: "output:assistant", role: "INTERVIEWER", content: "Next question" })
    const attachment = order.finalize({ providerEventId: "attachment:one", role: "PARTICIPANT", content: "Shared screenshot", attachmentId: "one" })
    expect(order.unresolved).toBe(true)
    expect(persist).not.toHaveBeenCalled()
    await order.finalize({ providerEventId: "input:user", role: "PARTICIPANT", content: "My previous answer" })
    await Promise.all([assistant, attachment])
    expect(persist.mock.calls.map(([event]) => event.providerEventId)).toEqual(["input:user", "output:assistant", "attachment:one"])
    expect(order.unresolved).toBe(false)
  })
  it("retains failed work and prevents later work from passing it until explicit retry", async () => {
    const save = vi.fn().mockRejectedValueOnce(new Error("offline")).mockResolvedValue(undefined)
    const queue = new VoiceSaveQueue<string>(save)
    await expect(queue.append("first")).rejects.toThrow("offline")
    await expect(queue.append("second")).rejects.toThrow("offline")
    await expect(queue.flush()).rejects.toThrow("offline")
    expect(save.mock.calls.map(([value]) => value)).toEqual(["first"])
    await queue.retry()
    await queue.flush()
    expect(save.mock.calls.map(([value]) => value)).toEqual(["first", "first", "second"])
  })
  it("flush waits for work added while an earlier save is running", async () => {
    let release!: () => void
    const save = vi.fn().mockImplementationOnce(() => new Promise<void>((resolve) => { release = resolve })).mockResolvedValue(undefined)
    const queue = new VoiceSaveQueue<string>(save)
    const first = queue.append("first")
    await Promise.resolve()
    const flushed = queue.flush()
    const second = queue.append("second")
    release()
    await Promise.all([first, second, flushed])
    expect(save).toHaveBeenCalledTimes(2)
  })
  it("updates captions by item ID instead of the most recent speaker bubble", () => {
    let state = reduceVoiceCaption([], { type: "response.output_audio_transcript.delta", item_id: "one", delta: "First" })
    state = reduceVoiceCaption(state, { type: "response.output_audio_transcript.delta", item_id: "two", delta: "Second" })
    state = reduceVoiceCaption(state, { type: "response.output_audio_transcript.done", item_id: "one", transcript: "First final" })
    expect(state).toEqual([{ id: "output:one", role: "INTERVIEWER", content: "First final", partial: false }, { id: "output:two", role: "INTERVIEWER", content: "Second", partial: true }])
  })
})
