ALTER TABLE "opportunities" ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
ALTER TABLE "solutions"     ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
ALTER TABLE "assumptions"   ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
ALTER TABLE "experiments"   ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
ALTER TABLE "objectives"    ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
ALTER TABLE "key_results"   ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
