/** Auditable MCP → REST ledger. It documents parity but never drives routing. */
export const MCP_PARITY_CATALOG = {
  toolCount: 191,
  sortedToolNamesSha256: "630c91148ac12679774466428bfce97b0cd4736e61a6edccf704c6cd8647a6ff",
} as const

export type McpRestParityDisposition =
  | { kind: "direct"; operationId: string }
  | { kind: "composition"; operationIds: readonly string[]; documentationAnchor: string; rationale: string }
  | { kind: "excluded"; category: "human-governance" | "execution-boundary" | "model-orchestration" | "transport-convenience"; documentationAnchor: string; restAlternative: string; rationale: string }

const docs = "docs/content/09-rest-api.md#mcp-parity-and-transport-exclusions"
const direct = (operationId: string): McpRestParityDisposition => ({ kind: "direct", operationId })
const composition = (operationIds: readonly string[], rationale: string): McpRestParityDisposition => ({ kind: "composition", operationIds, documentationAnchor: docs, rationale })
const excluded = (category: "human-governance" | "execution-boundary" | "model-orchestration" | "transport-convenience", restAlternative: string, rationale: string): McpRestParityDisposition => ({ kind: "excluded", category, documentationAnchor: docs, restAlternative, rationale })

export const MCP_REST_PARITY_MANIFEST = {
  activate_research_study: direct("activateResearchStudy"),
  add_assumption: direct("createAssumption"),
  add_comment: direct("createComment"),
  add_doc_comment: direct("createDocComment"),
  add_evidence: direct("createEvidence"),
  add_feedback_attachment: composition(["prepareFeedbackAttachmentUpload", "completeFeedbackAttachmentUpload"], "REST uses a bounded direct upload followed by receipt-verified completion; MCP-only inline base64 convenience is not exposed."),
  add_key_result: direct("createKeyResult"),
  add_solution: direct("createSolution"),
  add_solution_comment: direct("createSolutionPlanComment"),
  add_solution_plan: direct("createSolutionPlan"),
  add_to_roadmap: direct("createRoadmapItem"),
  apply_recorded_decision: excluded("execution-boundary", "Read the decision and update the authorized product resources explicitly.", "A receipt records externally completed work; exposing it as a REST mutation could be mistaken for execution authority."),
  approve_solution_plan: excluded("human-governance", "Read plan entries and request a tracked decision.", "Plan approval is a human judgment boundary and REST must not turn proposal review into an ordinary mutation."),
  archive_artifact: direct("archiveArtifact"),
  archive_metric: direct("archiveMetric"),
  archive_research_study: direct("archiveResearchStudy"),
  archive_scoring_model: direct("archiveScoringModel"),
  assign_squad: composition(["updateOpportunity", "updateExperiment", "updateRoadmapItem", "updateObjective", "updateTask"], "Assign through the PATCH operation for the selected resource type; no polymorphic RPC endpoint is needed."),
  capture_screenshot: excluded("execution-boundary", "Read the artifact resource; its stored thumbnail is captured server-side.", "Screenshot capture boots a Vercel Sandbox and renders a stored artifact revision in headless Chromium; that is an execution boundary REST must not expose as an ordinary resource mutation."),
  close_decision_no_action: excluded("human-governance", "Read the decision request and leave it pending for an authorized reviewer.", "No-action closure is a human judgment boundary rather than resource administration."),
  close_research_study: direct("closeResearchStudy"),
  conclude_experiment: direct("concludeExperiment"),
  create_artifact: direct("createArtifact"),
  create_card_sort_round: direct("createCardSortRound"),
  create_checklist_template: direct("createChecklistTemplate"),
  create_doc: direct("createDoc"),
  create_doc_version: direct("createDocVersion"),
  create_experiment: direct("createExperiment"),
  create_feedback: composition(["createFeedback", "prepareFeedbackAttachmentUpload", "completeFeedbackAttachmentUpload"], "Create plain feedback directly; feedback with attachments uses the bounded direct-upload workflow because inline base64 is MCP-only."),
  create_feedback_source: direct("createFeedbackSource"),
  create_metric: direct("createMetric"),
  create_objective: direct("createObjective"),
  create_okr_cycle: direct("createOkrCycle"),
  create_opportunity: direct("createOpportunity"),
  create_research_study: composition(["createResearchStudy", "activateResearchStudy"], "Create the draft resource, then use the explicit human activation action when the MCP call requests its default ACTIVE state and one-time participant link."),
  create_scoring_model: direct("createScoringModel"),
  create_squad: direct("createSquad"),
  create_task: direct("createTask"),
  create_workspace: direct("createWorkspace"),
  delete_assumption: direct("deleteAssumption"),
  delete_comment: direct("deleteComment"),
  delete_doc_comment: direct("deleteDocComment"),
  delete_key_result: direct("deleteKeyResult"),
  delete_objective: direct("deleteObjective"),
  delete_solution_comment: direct("deleteSolutionPlanEntry"),
  follow: direct("followResource"),
  generate_research_guide: excluded("model-orchestration", "Create or update the study's public metadata, then conduct sessions through the participant protocol.", "Guide generation exposes prompt/model workflow internals rather than a stable public resource contract."),
  generate_research_synthesis: direct("createResearchSynthesis"),
  get_artifact: direct("getArtifact"),
  get_card_sort_board: direct("getCardSortBoard"),
  get_card_sort_proposals: direct("listCardSortProposals"),
  get_card_sort_tally: direct("getCardSortTally"),
  get_comment: direct("getComment"),
  get_current_identity: direct("getCurrentIdentity"),
  get_custom_field_values: direct("listCustomFieldValues"),
  get_decision: direct("getDecision"),
  get_doc: direct("getDoc"),
  get_doc_comment: direct("getDocComment"),
  get_doc_version: direct("getDocVersion"),
  get_experiment: direct("getExperiment"),
  get_feedback_item: direct("getFeedback"),
  get_help: direct("getHelp"),
  get_launch_checklist: direct("getLaunchChecklist"),
  get_metric: direct("getMetric"),
  get_metric_binding: direct("getMetricBinding"),
  get_metric_observation: direct("getMetricObservation"),
  get_okr_cycle: direct("getOkrCycle"),
  get_opportunity: direct("getOpportunity"),
  get_opportunity_score: direct("getOpportunityScore"),
  get_pm_interview: direct("getPmInterview"),
  get_research_session: direct("getResearchSession"),
  get_research_study: direct("getResearchStudy"),
  get_review_request: direct("getReviewRequest"),
  get_scoring_model: direct("getScoringModel"),
  get_solution_comment: direct("getSolutionPlanEntry"),
  get_solution_score: direct("getSolutionScore"),
  get_squad: direct("getSquad"),
  get_task: direct("getTask"),
  get_workspace_by_slug: direct("getWorkspaceBySlug"),
  get_workspace_scoring_model: direct("getWorkspaceScoringModel"),
  get_workspace_summary: direct("getWorkspaceSummary"),
  issue_research_link: direct("issueResearchParticipantLink"),
  link_artifact_to_decision: direct("linkArtifactDecision"),
  link_artifact_to_solution: direct("linkArtifactSolution"),
  link_evidence: direct("updateEvidenceTarget"),
  link_feedback_to_opportunity: direct("updateFeedback"),
  link_metric: direct("createMetricBinding"),
  link_opportunity_to_kr: direct("updateOpportunity"),
  link_opportunity_to_objective: direct("linkOpportunityObjective"),
  link_solution_to_key_result: direct("linkSolutionKeyResult"),
  link_task: direct("linkTaskResource"),
  list_analytics_connections: direct("listAnalyticsConnections"),
  list_artifacts: direct("listArtifacts"),
  list_assumptions: direct("listAssumptions"),
  list_card_sort_factors: direct("listCardSortFactors"),
  list_card_sort_rounds: direct("listCardSortRounds"),
  list_checklist_templates: direct("listChecklistTemplates"),
  list_comments: direct("listComments"),
  list_custom_field_definitions: direct("listCustomFieldDefinitions"),
  list_decisions: direct("listDecisions"),
  list_doc_comments: direct("listDocComments"),
  list_doc_versions: direct("listDocVersions"),
  list_docs: direct("listDocs"),
  list_eligible_parent_key_results: direct("listEligibleParentKeyResults"),
  list_evidence: direct("listEvidence"),
  list_experiments: direct("listExperiments"),
  list_feedback: direct("listFeedback"),
  list_links: direct("listEntityLinks"),
  list_metric_bindings: direct("listMetricBindings"),
  list_metric_observations: direct("listMetricObservations"),
  list_metrics: direct("listMetrics"),
  list_notifications: direct("listNotifications"),
  list_okr_cycles: direct("listOkrCycles"),
  list_opportunities: direct("listOpportunities"),
  list_release_runs: direct("listReleaseRuns"),
  list_research_sessions: direct("listResearchSessions"),
  list_research_studies: direct("listResearchStudies"),
  list_research_syntheses: direct("listResearchSyntheses"),
  list_review_requests: direct("listReviewRequests"),
  list_roadmap_items: direct("listRoadmapItems"),
  list_scoring_models: direct("listScoringModels"),
  list_solution_comments: direct("listSolutionPlanEntries"),
  list_solutions: direct("listSolutions"),
  list_squads: direct("listSquads"),
  list_task_assignees: direct("listTaskAssignees"),
  list_task_links: direct("listTaskLinks"),
  list_tasks: direct("listTasks"),
  list_top_opportunities: composition(["listWorkspaceOpportunityRankings", "listOrganizationOpportunityRankings"], "Dispatch to the workspace or organization ranking collection matching the MCP tool's mutually exclusive tenant scope."),
  list_workspaces: direct("listOrganizationWorkspaces"),
  log_checkin: direct("createCheckIn"),
  log_experiment_result: direct("createExperimentResult"),
  mark_read: direct("markNotificationsRead"),
  move_task_status: direct("updateTask"),
  prepare_doc_image_upload: direct("prepareDocImageUpload"),
  prepare_feedback_attachment_upload: direct("prepareFeedbackAttachmentUpload"),
  promote_feedback_to_roadmap: direct("promoteFeedbackToRoadmap"),
  promote_research_finding_to_evidence: direct("promoteResearchEvidence"),
  promote_to_roadmap: direct("promoteSolutionToRoadmap"),
  propose_card_sort_move: direct("proposeCardSortMoves"),
  refresh_metric_binding: direct("refreshMetricBinding"),
  reject_solution_plan: excluded("human-governance", "Read plan entries and request a tracked decision.", "Plan rejection is a human judgment boundary and REST must not turn proposal review into an ordinary mutation."),
  reopen_comment: direct("reopenComment"),
  reopen_doc_comment: direct("reopenDocComment"),
  request_decision: direct("requestDecision"),
  request_release_authorization: direct("requestReleaseAuthorization"),
  resolve_comment: direct("resolveComment"),
  resolve_doc_comment: direct("resolveDocComment"),
  restore_doc_version: direct("restoreDocVersion"),
  revoke_research_links: direct("revokeResearchParticipantLinks"),
  rotate_research_link: direct("rotateResearchParticipantLink"),
  score_opportunity: direct("scoreOpportunity"),
  score_solution: direct("scoreSolution"),
  search_help: direct("searchHelp"),
  set_card_sort_round_state: composition(["revealCardSortRound", "closeCardSortRound"], "Use the explicit irreversible reveal or close action; REST has no generic state PATCH or unreveal operation."),
  set_custom_field_value: direct("setCustomFieldValue"),
  set_launch_tier: direct("setLaunchTier"),
  set_objective_parent_kr: direct("updateObjective"),
  set_workspace_scoring_model: direct("updateWorkspaceScoringModel"),
  unfollow: direct("unfollowResource"),
  unlink_artifact_from_decision: direct("unlinkArtifactDecision"),
  unlink_artifact_from_solution: direct("unlinkArtifactSolution"),
  unlink_metric: direct("deleteMetricBinding"),
  unlink_opportunity_from_objective: direct("unlinkOpportunityObjective"),
  unlink_solution_from_key_result: direct("unlinkSolutionKeyResult"),
  unlink_task: direct("unlinkTaskResource"),
  update_artifact: direct("updateArtifact"),
  update_assumption: direct("updateAssumption"),
  update_comment: direct("updateComment"),
  update_doc: direct("updateDoc"),
  update_doc_comment: direct("updateDocComment"),
  update_experiment: direct("updateExperiment"),
  update_feedback: direct("updateFeedback"),
  update_feedback_source: direct("updateFeedbackSource"),
  update_feedback_status: direct("updateFeedback"),
  update_feedback_type: direct("updateFeedback"),
  update_key_result: direct("updateKeyResult"),
  update_launch_checklist_item: direct("updateLaunchChecklistItem"),
  update_metric: direct("updateMetric"),
  update_metric_binding: direct("updateMetricBinding"),
  update_objective: direct("updateObjective"),
  update_opportunity: direct("updateOpportunity"),
  update_opportunity_status: direct("updateOpportunity"),
  update_research_study: direct("updateResearchStudy"),
  update_roadmap_item: direct("updateRoadmapItem"),
  update_scoring_model: direct("updateScoringModel"),
  update_solution: direct("updateSolution"),
  update_solution_comment: direct("updateSolutionPlanEntry"),
  update_solution_status: direct("updateSolution"),
  update_squad: direct("updateSquad"),
  update_task: direct("updateTask"),
  withdraw_card_sort_proposal: direct("withdrawCardSortProposal"),
} as const satisfies Record<string, McpRestParityDisposition>
