import { test, expect, fixture } from "./fixtures"
test("authenticated workspace navigation fits the viewport", async ({ page }, info) => {
  const f = fixture()
  await page.goto(`/${f.orgSlug}/${f.workspaceSlug}`)
  await expect(page).not.toHaveURL(/\/login/)
  await expect(page.locator('[data-slot="sidebar-inset"]')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: `preview-report/${info.project.name}-workspace.png` })
})
test("Light Dark and System persist, follow OS changes, and keep navigation and menus usable", async ({ page }) => {
  const f = fixture()
  await page.emulateMedia({ colorScheme: "light" })
  await page.goto(`/${f.orgSlug}/${f.workspaceSlug}/settings`)
  // Intentionally required: PR156 must land before this suite can pass on main.
  const theme = page.getByRole("group", { name: "Color theme" })
  await expect(theme).toBeVisible()
  await theme.getByRole("button", { name: "Dark", exact: true }).click()
  await page.reload()
  await expect(theme.getByRole("button", { name: "Dark", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect(page.locator("html")).toHaveClass(/\bdark\b/)
  // Explicit preferences override the OS, including after a reload.
  await page.emulateMedia({ colorScheme: "dark" })
  await theme.getByRole("button", { name: "Light", exact: true }).click()
  await page.reload()
  await expect(theme.getByRole("button", { name: "Light", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect(page.locator("html")).not.toHaveClass(/\bdark\b/)
  await theme.getByRole("button", { name: "System", exact: true }).click()
  await page.reload()
  await expect(theme.getByRole("button", { name: "System", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect.poll(() => page.evaluate(() => localStorage.getItem("compass-theme"))).toBe("system")
  await expect(page.locator("html")).toHaveClass(/\bdark\b/)
  await page.emulateMedia({ colorScheme: "light" })
  await expect(page.locator("html")).not.toHaveClass(/\bdark\b/)
  await page.emulateMedia({ colorScheme: "dark" })
  await expect(page.locator("html")).toHaveClass(/\bdark\b/)

  const mobile = page.viewportSize()!.width < 768
  const navigation = page.getByRole("navigation", { name: mobile ? "Primary navigation" : "Main navigation", exact: true })
  await expect(navigation).toBeVisible()
  await expect(page.getByRole("navigation", { name: mobile ? "Main navigation" : "Primary navigation", exact: true })).toBeHidden()
  await navigation.getByRole("link", { name: "Discovery", exact: true }).click()
  await expect(page).toHaveURL(/\/discovery$/)
  await expect(page.locator("html")).toHaveClass(/\bdark\b/)
  await page.getByRole("button", { name: mobile ? "Account" : "Account menu", exact: true }).click()
  const menu = page.getByRole("menu")
  await expect(menu).toBeVisible()
  const bounds = await menu.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width + 1)
  expect(await menu.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  expect(await menu.evaluate(element => getComputedStyle(element).backgroundColor)).not.toBe("rgb(255, 255, 255)")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1 && document.body.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.keyboard.press("Escape")
  await expect(menu).toBeHidden()
})
